global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'fastapi-users-service'
    static_configs:
      - targets: ['fastapi_users_service:8000']
    metrics_path: '/metrics'
