global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - payment-failure-alert.yaml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmgr:9093']

scrape_configs:
  - job_name: 'fastapi-users-service'
    static_configs:
      - targets: ['fastapi_users_service:8000']
    metrics_path: '/metrics'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8089']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
