"""update models

Revision ID: 1e79a25fffcb
Revises: 26e49c958d97
Create Date: 2026-01-08 00:29:35.370365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e79a25fffcb'
down_revision: Union[str, None] = '26e49c958d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refreshtoken_user_id_fkey', 'refreshtoken', type_='foreignkey')
    op.create_foreign_key(None, 'refreshtoken', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refreshtoken', schema='public', type_='foreignkey')
    op.create_foreign_key('refreshtoken_user_id_fkey', 'refreshtoken', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
