"""add refresh_tokens

Revision ID: 26e49c958d97
Revises: c79a52df32ab
Create Date: 2026-01-03 03:06:05.792058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e49c958d97'
down_revision: Union[str, None] = 'c79a52df32ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_refreshtoken_token'), 'refreshtoken', ['token'], unique=True, schema='public')
    op.create_index(op.f('ix_public_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_refreshtoken_user_id'), table_name='refreshtoken', schema='public')
    op.drop_index(op.f('ix_public_refreshtoken_token'), table_name='refreshtoken', schema='public')
    op.drop_table('refreshtoken', schema='public')
    # ### end Alembic commands ###
