name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Optional Docker image tag"
        required: false

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: tareqmonwer/fastapi-users-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Determine Docker tag
        id: tag
        run: |
          if [ "${{ github.event.inputs.docker_tag }}" ]; then
            echo "tag=${{ github.event.inputs.docker_tag }}" >> $GITHUB_ENV
          else
            echo "tag=dev-${{ github.run_id }}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$tag .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$tag
